### ISSUE TITLE
The package is not working on Windows because of trying to create a folder name containing a colon (time format)

### ISSUE THREAD

**Issue by barpaw** [mogluszka/evaluateCutpoints#1]
The package is not working on Windows because of trying to create a folder name containing a colon (time format)

https://github.com/mogluszka/evaluateCutpoints/blob/376700d86a9c2334879719d71dfc36de0b65775f/R/evaluate-cutpoints.R#L130

This method returns time-formated string with colon `"niedz. wrz 11 2022 17:58:02"` which is used as the folder name. Windows does not allow the folder name to contain a colon.

Simple fix ( use lowercase x ):
` currentDate <- format(Sys.time(), "%a %b %d %Y %x") `

**Comment by tsikup** [comment]
With this change, the output format for MacOS Monterey gives the following output:

`format(Sys.time(), "%a %b %d %Y %x")` -> `Fri Dec 23 2022 23/12/2022`

Due to the `/`, dir.create(currentDate) fails since it detects `Fri Dec 23 2022 23/12/2022` as 3 different folders, the former of which are not recursively created.

A solution that would work for both Windows and Unix systems would be `currentDate <- format(Sys.time(), "%a %b %d %Y %H %M %S")`.
